In [17]:
import pandas as pd


pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)


df = pd.read_csv('/content/student_performance.csv')
display(df)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [2]:
import pandas as pd
df = pd.read_csv('/content/student_performance.csv')
df.head(5)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [5]:

col_name = df.columns[4]

print(f"Shape of the 5th column ('{col_name}'): {df.iloc[:, 4].shape}")

Shape of the 5th column ('department'): (30,)

In [4]:

row_shape = df.iloc[4].shape
print(f"Shape of the 5th row: {row_shape}")

display(df.iloc[[4]])

Shape of the 5th row: (13,)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [6]:

print(df.columns.tolist())

['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [7]:

column_count = len(df.columns)
print(f"Total number of columns: {column_count}")

Total number of columns: 13

In [8]:

display(df.dtypes)

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [9]:
display(df.describe(include='all'))

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
count,30.000000,30,30.000000,30,30,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30,30.0
unique,NaN,30,NaN,2,4,NaN,NaN,NaN,NaN,NaN,NaN,25,NaN
top,NaN,Aarav Sharma,NaN,Male,Computer Science,NaN,NaN,NaN,NaN,NaN,NaN,Kochi,NaN
freq,NaN,1,NaN,15,13,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
mean,1015.500000,NaN,19.733333,NaN,NaN,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,NaN,2023.0
std,8.803408,NaN,0.739680,NaN,NaN,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,NaN,0.0
min,1001.000000,NaN,19.000000,NaN,NaN,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,NaN,2023.0
25%,1008.250000,NaN,19.000000,NaN,NaN,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,NaN,2023.0
50%,1015.500000,NaN,20.000000,NaN,NaN,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,NaN,2023.0
75%,1022.750000,NaN,20.000000,NaN,NaN,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,NaN,2023.0
max,1030.000000,NaN,21.000000,NaN,NaN,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,NaN,2023.0

In [10]:
display(df.isnull().sum())

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [11]:
import numpy as np

for i in range(6):
    row = np.random.randint(0, len(df))
    col = np.random.randint(0, len(df.columns))
    df.iat[row, col] = np.nan

display(df.isnull().sum())

student_id               0
name                     1
age                      0
gender                   1
department               0
semester                 0
math_score               0
science_score            2
english_score            0
programming_score        0
attendance_percentage    0
city                     1
admission_year           0
dtype: int64

In [14]:
import pandas as pd

deleted_indices = df.sample(n=5).index

deleted_rows = df.loc[deleted_indices]

df = df.drop(index=deleted_indices)

print(f"Deleted index: {deleted_indices.tolist()}")
print("\nDeleted Rows:")
display(deleted_rows)

print(f"\n new rows: {len(df)}")

Deleted index: [19, 20, 13, 25, 6]

Deleted Rows:

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84.0,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70.0,67,58,74,Thiruvananthapuram,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78.0,82,51,91,Thrissur,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77.0,73,63,82,Kochi,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69.0,65,40,85,Bangalore,2023

 new rows: 15

In [15]:
unique_departments = df['department'].unique()
print("Unique Departments:")
display(unique_departments)

Unique Departments:

array(['Computer Science', 'Mechanical', 'Electronics', 'Civil'],
      dtype=object)

In [16]:
dept_counts = df['department'].value_counts()

print("Number of students per department:")

display(dept_counts)

Number of students per department:

department
Computer Science    6
Civil               4
Electronics         3
Mechanical          2
Name: count, dtype: int64

In [18]:
city_counts = df['city'].value_counts()

print("Number of students per city:")
display(city_counts)

Number of students per city:

city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [21]:
chennai_mumbai_students = df[df['city'].isin(['Chennai','Mumbai'])]
display(chennai_mumbai_students[['student_id', 'name', 'city', 'programming_score']])

    student_id          name     city  programming_score
0         1001  Aarav Sharma   Mumbai                 91
10        1011   Vikram Iyer  Chennai                 72

In [27]:
low_attendance = df[df['attendance_percentage'] > 50]
display(low_attendance)
low  = df['attendance_percentage'].value_counts()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [34]:
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
display(df.head())

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,326
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023,325
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023,255
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023,273
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,356

In [33]:
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
tp = df.loc[df['total_score'].idxmin()]
display(tp)

student_id                       1017
name                     Manoj Pandey
age                                21
gender                           Male
department                      Civil
semester                            2
math_score                         56
science_score                      61
english_score                      55
programming_score                  38
attendance_percentage              65
city                            Patna
admission_year                   2023
total_score                       210
Name: 16, dtype: object